### ISSUE TITLE
Implement backoff per AWS expectations

### ISSUE THREAD

**Issue by jtkinser** [awspilot/dynamodb-oop#14]
Could you please implement backoff and retry capbabilites per http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ErrorHandling.html#APIRetries

If it already exists, could you information about it to the documentation?

**Comment by databank** [comment]
Hi,

One way you could do this atm is to pass in the DynamoDB instance like this:

var $db = new AWS.DynamoDB({maxRetries: 5});
var DynamoDB = require('aws-dynamodb')($db);

or 

configure maxRetries globally:
AWS.config.maxRetries = 5

It looks like AWS allows a bit of controlling Error Retries

```
AWS.events.on('retry', function(resp) {
     if (resp.error && resp.error.retryable) {
          resp.error.retryDelay = 5000; // delay it (see resp.retryCount )
          resp.error.retryable = false; // or cancel retry
     }
});
```

I will look more into it, see if I can come up with something that makes sense
sure would be nice to be able to do DynamoDB.table().insert({...}, callback).on('retry', retryCallback )

but I think this is not available per request

I'll look more into this, any suggestions welcomed 

-adrian

**Comment by jtkinser** [comment]
Great thanks! You might check out how it was implemented in this library: https://github.com/jed/dynamo-client
