### ISSUE TITLE
InvalidParameterType

### ISSUE THREAD

**Issue by randeepbhatia** [awspilot/dynamodb-oop#25]
Hi
When I try to perform the query by using .select(DynamoDB.ALL). 
It raises exception 
{ [InvalidParameterType: Expected params.AttributesToGet[0] to be a string]
  message: 'Expected params.AttributesToGet[0] to be a string',
  code: 'InvalidParameterType',
  time: Tue Jun 07 2016 23:30:16 GMT-0700 (PDT) }

**Comment by databank** [comment]
can you try DynamoDB.ALL_ATTRIBUTES please and let me know it that worked

**Comment by databank** [comment]
Also "DynamoDB" part of DynamoDB.ALL should be the name of your aws-dynamodb object instance

DynamoDB.table(...).select( DynamoDB.ALL )
or
varname.table('...').select( varname.ALL )

**Comment by randeepbhatia** [comment]
This is my global var
var DynamoDB = require('aws-dynamodb')(config.AWS_CONFIG);
And i have tried both ALL_ATTRIBUTES & ALL, it raises me same exception.
Also is it only supposed to work with queries or it can work with table scans also.

**Comment by databank** [comment]
please try to run the same with logging on
```
DynamoDB.on('error', function( operation, error, payload ) {
    console.log( operation, error, payload )
})

```
remove the actual data from the payload and paste it here

**Comment by databank** [comment]
Im closing this, please re-open if you still have the issue.thanks
