### ISSUE TITLE
Empty array getting returned from DB

### ISSUE THREAD

**Issue by randeepbhatia** [awspilot/dynamodb-oop#27]
Hi I believe its part of a the recent update, of all my dynamodB requests, I see one last object to be completely empty.
It's happening with the scan operation.

DynamoDB.table('TableName') 
        .scan (function (err, data) {
            if (err) {
                cb(err, null);
            }
            cb(null, data);
        });

**Comment by databank** [comment]
sorry for the late reply, I just noticed your post now,

can you provide details on how to reproduce this ?

also note that your error handling is missing the return:

```
if (err)
   return cb(err, null )
```

**Comment by TimMeade** [comment]
I'm seeing this a lot.....  if I rerun something simple insert 2 of 5 will come back {}

**Comment by databank** [comment]
Im closing it, I'm supposing empty data is because of the leftout "return"
