### ISSUE TITLE
update or insert is modifying my data object

### ISSUE THREAD

**Issue by teebu** [awspilot/dynamodb-oop#30]
The ASIN is also the main key of the table.

update or insert data: 
```{"ASIN":"B00CIDQ470","date_set_at":"2016-11-23T22:03:53.100Z","lowestPrice":51.59}```

object after update:
```
{ date_set_at: '2016-11-23T22:03:53.100Z', lowestPrice: 51.59 }
```

I've solved it by cloning the data object and using the clone instead, but I dont think it should be modifying my object.

```
function update_or_insert_item(key, value, data, callback) {
  var tmp_data = _.clone(data) // it's removing ASIN if i dont clone it
  console.log('update or insert data: %j', tmp_data)
  DynamoDB
    .table(dynamoTable)
    .where(key).eq(value)
    .return(DynamoDB.NONE)
    .insert_or_update(tmp_data, function (err, res) {
      if (err) {
        console.log(err, res)
      }
      //console.log( 'update result:', err, res )
      //console.log(this.ConsumedCapacity)
      return callback(err, res)
    })
}
```

**Comment by databank** [comment]
You're right, that should never happen!

Will spawn a new version asap

Thanks for reporting

**Comment by databank** [comment]
I could only found this issue with insert_or_update()

fixed and published 0.1.61

I'm closing the issue, please re-open it if you're still seeing the problem

`</adrian>`

**Comment by teebu** [comment]
i see you used clone, is it a deep clone or shallow clone? did you test for both?

**Comment by databank** [comment]
I think shallow clone will work just fine as long as
nested properties are not modified by the insert_or_update()

everything looks good in the tests just hoping I have not omitted anything
