### ISSUE TITLE
Raising an issue to tell ...

### ISSUE THREAD

**Issue by fxpiteam** [awspilot/dynamodb-oop#31]
... that this is by far THE BEST EVER DynamoDB wrapper I've worked with. Thanks a million for your efforts.
I know there is still a lot of work to be done on the same, but, the API coverage and the ease of development after using this should be appreciated.

Thanks...

**Comment by databank** [comment]
Happy to hear it, keeps me going. Thanks !!!

I'll close the "issue" now :)
