### ISSUE TITLE
Promise support

### ISSUE THREAD

**Issue by damonmaria** [awspilot/dynamodb-oop#33]
Having a look through the source for `routeCall` it looks like this package can't be used with promises (by not passing a callback and calling `.promise()` on the AWS SDK service call result). Which is a shame given I love the resulting 'language' this package creates on top of DynamoDB. That callbacks are used internally in `dynamodb.js` might make supporting promises and callbacks a bit of a refactor. Are there any other reasons promises aren't supported?

**Comment by databank** [comment]
Hi Maria,

It's in my todo list, It should not be difficult to add
just like you said by not passing the callback.

The main concern is that it may create braking changes.

Even myself I've used this library without passing a callback
knowing that it wont throw an error if it fails
(for example when incrementing stats).

Now, in a promise world, I should add the .catch()
wherever I've not passed a callback.

I'm also considering
```
DynamoDB
	.table(...)
	.insert(...)
	.on('err',...)
	.on('data',...)
	.on('duplicate',...)
```

or 

```
DynamoDB
	.table(...)
	.scan(...)
	.each( callback )
```

but Promise seems more widely adopted

--------------

 I guess Promise may be coming soon :)

**Comment by damonmaria** [comment]
Sounds good. I was thinking through how I would do this and thought that the internal callbacks, if broken down into 'onError', 'transformData', etc., could be applied to either the promise `then()` or the callback. As is with multiple functionality (including the calling the caller's callback) wrapped up in the internal callbacks it's just not possible. 

Ever since moving to `async`/`await` world I always try and develop with promises now since it's so much less error prone.

**Comment by adrianpraja** [comment]
I've added Promise for .get() .query() and .scan() using the "promise" npm

```
DynamoDB
	.table(...)
	.where(...).eq(...)
	.query()
	.then(success_cb, fail_cb)
	.catch(fail_cb)
```


If you;re still using the library please let let me know if you see any issues 
using it.

It is a test release , my tests shows that it does not break existing functionality,
it is not documented yet, the rest of the functionality should get Promise() soon

**Comment by adrianpraja** [comment]
Im closing this as the last release includes unpromised Promises :-)
