### ISSUE TITLE
Docs scroll to top

### ISSUE THREAD

**Issue by RaneIO** [awspilot/dynamodb-oop#35]
Docs scroll to top when I highlight something in Ace editor and click. New version of Ace fix this issue. I test with Mac+Chrome.

Temporary docs: https://dynamodb-oop-cwaugdipby.now.sh/

**Comment by adrianpraja** [comment]
Thanks, I''ll update as soon as I get to the computer.

**Comment by adrianpraja** [comment]
Ace is now version 1.2.6 👍
