### ISSUE TITLE
Executing an average operation on the DB

### ISSUE THREAD

**Issue by Vadorequest** [awspilot/dynamodb-oop#37]
I have a table `feedback` with a `rating` field, which is a number.

I'd like to get the average value of this field, is there any simple way of doing it? So far I only see a `query` which gets all the rows and do the average calculation once they've all been retrieved.

**Comment by adrianpraja** [comment]
Unfortunately this is not supported by Amazon DynamoDB at this time

You must query the data and do the calculations yourself 
I suggest creating a GSI index, with only rating field projected 
and then query that index
this way might fit everything into the 1 MB data limit per query/scan
so you don't need to make other calls to get the remaining data
