### ISSUE TITLE
Looping Scan with async/await question.

### ISSUE THREAD

**Issue by teebu** [awspilot/dynamodb-oop#40]
```
async function ScanDynamodbTable(lastKey) {
	return await DynamoDB.table('mytable')
		.resume(lastKey)
		.limit(1)
		.scan()
}
``` 

Returns a single array object. But if I wanted to resume scanning, it comes from the `this.LastEvaluatedKey` which can only be obtained from within scan. 

Basically, i want to create a do while loop with async/await, because recursion with promises has a memory leak, and I can't seem to get the LastEvaluatedKey.

**Comment by adrianpraja** [comment]
Hi Teebu,

you can also construct the LastEvaluatedKey from be the last item returned by the scan,
suppose you have a table with key hash String, range Number and scan returns 100 items:

```  
LastEvaluatedKey = { 
	hash: {
		S: data[99].hash 
	},
	range: {
		N: data[99].hash.toString()
	}
}
```

Of course if you set a limit and you get less items in the result then it makes no sense to continue scan;

I never tested with async, I'll give it a try the next days.

**Comment by teebu** [comment]
I couldn't figure it out, so I ended up using callbacks as a temporary solution. It's not a clean solution, but works for now.

```
function ScanDynamodbTable(lastKey=null, callback) {
	let results;
	DynamoDB.table('AppAdviceProdSNS')
		.resume(lastKey)
		.limit(2)
		.scan(function(err, data) {
			let result = { data: data, LastEvaluatedKey: this.LastEvaluatedKey }
			return callback(err, result)
		})
}
```

**Comment by teebu** [comment]
I re-read your message, is the LastEvaluatedKey, basically the `Primary partition key`'s value?
