### ISSUE TITLE
Update table

### ISSUE THREAD

**Issue by Vadorequest** [awspilot/dynamodb-oop#43]
I wonder if this lib can perform operation such as UpdateTable: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB.html#updateTable-property

I couldn't find such method in the doc http://awspilot.github.io/dynamodb-oop/

**Comment by adrianpraja** [comment]
Indeed there is no wrap around updateTable you must call aws-sdk directly

```
DynamoDB.client.updateTable( params, cb )
```

createTable, updateTable and deleteTable It is in my todo list for the SQL part of this lib

there used to be **CREATE TABLE** in the [old sql version](https://github.com/awspilot/dynamodb-sql)

but that is deprecated and wont get new updates;

**Comment by Vadorequest** [comment]
Thanks!
