### ISSUE TITLE
Support to pass array of attribute names for "select" operand

### ISSUE THREAD

**Issue by a-dorogov** [awspilot/dynamodb-oop#44]
Hello
Could you please add this feature
`dynamoDb
	.table("table")
	.select( ["attribute1", "attribute2", ...] )
`

Thanks

**Comment by adrianpraja** [comment]
Hi Alexander,

Agree, makes total sense.

Just checked, I thought I can easily do `select.apply(scope, ["attribute1", "attribute2", ...] )`
but there;s no way to pass the scope without splitting the code 

I will add this to the next release

**Comment by adrianpraja** [comment]
Alexander,

in `v1.2.10` you can now pass an Array as argument to `.select()`

Please re-open if anything looks inproper

Thanks
</adrian>
