### ISSUE TITLE
Support Dynamo Transactions

### ISSUE THREAD

**Issue by jadbox** [awspilot/dynamodb-oop#49]
This would be a big help to my app as Dynamo Transactions opens up a lot of use cases.

**Comment by adrianpraja** [comment]
I have no idea how it shoul look 

thinking something like:

```
DynamoDB
	.transaction()

		// putItem  
		.table('a').insert({...}) // insert if not exists 
		.table('b').insert_or_replace({...}) 
		.table('c').replace({...}) // replace only if exists 

		// updateItem
		.table('d').where('hash').eq('h')..if('active').eq(true).update({...}) // update existing item
		.table('e').insert_or_update({...})

		// deleteItem
		.table('f').where('hash').eq('h').if('disabled').eq(true).delete() 

	.write(function( err, data ) {
		console.log( err, data )
	});

```

**Comment by jadbox** [comment]
That looks good to me offhand. Some ORMs use a terminator like `.commit()`, but I'm not sure if it's actually useful for this use-case.

Example:
```
DynamoDB
	.transaction()
		// putItem  
		.table('a').insert({...}) // insert if not exists 
		.table('b').insert_or_replace({...}) 
		.table('c').replace({...}) // replace only if exists 
        .commit()
	.write(function( err, data ) {
		console.log( err, data )
	});
```

**Comment by jadbox** [comment]
Also here an alternative to the transaction API, but again I'm not sure if it's any better functionally:
```js
DynamoDB
	.transaction( o =>
		o.table('a').insert({...}) // insert if not exists 
        )
	.write(function( err, data ) {
		console.log( err, data )
	});
```

**Comment by adrianpraja** [comment]
It would be either `.commit()` or `.write()`
since AWS's operation is called `TransactWriteItems` 
I thought  `.write()` will make more sense.

The `.transaction( o => ... )` would also work; 
It's actually a good idea I could use for the `.where()` OR issue,
currently all `.where()`s are ANDed together with no OR support

Thanks, I'll publish 1.5.2 with some sort of transactions support these days

**Comment by jadbox** [comment]
@adrianpraja Thanks for the update. I'm looking forward to transaction support as I want to move from some RDS features to Dynamo, but it requires transactional support. I'm going to wait until 1.5.2 unblocks me to finish the ticket.

**Comment by adrianpraja** [comment]
Experimental transactions support added in v2.0.0
