### ISSUE TITLE
transact.insert is undefined on Lambda Layer

### ISSUE THREAD

**Issue by sizuhiko** [awspilot/dynamodb-oop#51]
I use Lambda Layer `arn:aws:lambda:ap-northeast-1:452980636694:layer:awspilot-dynamodb-2_0_0-beta:1`.

I have problem while transaction on the layer.
Example followings:

```js
const DynamoDB = require('@awspilot/dynamodb');

exports.handler = async (event) => {
    const db = DynamoDB({});
    db.schema({
      TableName: "my-table",
      KeySchema: [{ KeyType: 'HASH', AttributeName: 'id' }],
    });
    const tran = db.transact();
    const table = tran.table("my-table");
    console.log(table);
    console.log(table.insert);

    const response = {
        statusCode: 200,
        body: JSON.stringify('Hello from Lambda!'),
    };
    return response;
};
```

The outputs were followings:

```
INFO	Transact {
  pending: { tableName: 'my-table' },
  TransactItems: [],
  // Omited....
}
INFO	undefined
```

`insert` method undefineded.

I have unittest code on local.
The local environment using npm package.
I added logging to unittest code samely.

The local environment outputs were folliowings:

```
  console.log
    Transact {
      pending: { tableName: 'my-table' },
      TransactItems: [],
      // Omited....
    }

  console.log
    insert [Function]
```

In this case `insert` is function and callable.

Can I use transact.insert on Lambda Layer ?

===

- Node version: 12

**Comment by adrianpraja** [comment]
Sorry for the long reply delay,

The layer version is behind the npm version, that might be the explanation.
I will check and get back to you with.

**Comment by adrianpraja** [comment]
I've published updated lambda layer

arn:aws:lambda:ap-northeast-1:452980636694:layer:awspilot-dynamodb-2_0_0:1

Please let me know if the issue persists
